FROM centos

# Install any necessary packages
RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN  yum update -y && \
     yum install -y yum-utils && \
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
     yum update -y && \
     yum install -y \
     vim nano python3 zip unzip \
     docker-ce \
     docker-ce-cli \
     containerd.io \
     docker-buildx-plugin \
     docker-compose-plugin && \
     yum clean all && \
     rm -rf /var/cache/yum
     
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip

COPY amazon-corretto-15.0.2.7.1-linux-x64 /usr/src/app/amazon-coretto-jdk
ENV JAVA_HOME=/usr/src/app/amazon-coretto-jdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Add a command that runs continuously
CMD tail -f /dev/null
